window.sr = ScrollReveal({ reset:true});
ScrollReveal({ distance: '15px' });
sr.reveal('.inicio__fig', {duration : 3000, origin: 'right'});
sr.reveal('.inicio__texto', {duration : 3000, origin: 'left'});
sr.reveal('.inicio__texto2', {duration : 3000, origin: 'left'});
sr.reveal('.link-linkedin', {duration : 3000, origin: 'left'});
sr.reveal('.cursos__titulo', {duration : 3000, origin: 'right'});
sr.reveal('.cursos__item', {duration : 5000, origin: 'left'});
sr.reveal('.projetos__titulo', {duration : 3000, origin: 'right'});
sr.reveal('.projetos__caixa', {duration : 5000, origin: 'left'});
sr.reveal('.projetos__botao-vermais', {duration : 3000, origin: 'right'});
sr.reveal('.habilidades__titulo', {duration : 3000, origin: 'right'});
sr.reveal('.caixa-icone', {duration : 3000, origin: 'left'});
sr.reveal('.caixa-exibicao__titulo', {duration : 3000, origin: 'right'});
sr.reveal('.caixa-exibicao__img', {duration : 3000, origin: 'right'});
sr.reveal('.caixa-exibicao__descricao', {duration : 3000, origin: 'right'});
sr.reveal('.rodape', {duration : 3000, origin: 'bottom'});